version: '2'
distribution_spec:
  description: home.glroland.com's LLama Stack Distribution for Smart Lab Applications
  container_image: registry.access.redhat.com/ubi9/python-311:9.6-1747333117
  providers:
    inference:
    - remote::ollama
    - inline::sentence-transformers
#    - remote::vllm
#    - remote::openai
    vector_io:
    - inline::faiss
    - remote::milvus
#    - remote::pgvector
    safety:
    - inline::llama-guard
    agents:
    - inline::meta-reference
    telemetry:
    - inline::meta-reference
    eval:
    - inline::meta-reference
    datasetio:
    - remote::huggingface
    - inline::localfs
    scoring:
    - inline::basic
    - inline::llm-as-judge
    - inline::braintrust
    tool_runtime:
    - remote::tavily-search
    - inline::rag-runtime
    - remote::model-context-protocol
image_type: container
