apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-llama-stack.fullname" . }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-log-svc"}]'
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-my-llama-stack"
    {{- include "my-llama-stack.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-llama-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-llama-stack.selectorLabels" . | nindent 8 }}
    spec:
      {{- if eq .Values.image.usePullSecret true }}
      imagePullSecrets:
      - name: {{ include "my-llama-stack.fullname" . }}-pull-secret
      {{- end }}
      {{ if eq .Values.useServiceAccount true }}
      serviceAccountName: {{ include "my-llama-stack.fullname" . }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.port }}
          env:
            - name: LLAMA_STACK_PORT
              value: "{{ .Values.image.port }}"
            - name: LLAMA_STACK_LOGGING
              value: "all=debug"
            - name: INFERENCE_MODEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-llama-stack.fullname" . }}
                  key: INFERENCE_MODEL
            - name: EMBEDDING_MODEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-llama-stack.fullname" . }}
                  key: EMBEDDING_MODEL
            - name: OLLAMA_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-llama-stack.fullname" . }}
                  key: OLLAMA_URL
            - name: MILVUS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-llama-stack.fullname" . }}
                  key: MILVUS_ENDPOINT
            - name: MILVUS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-llama-stack.fullname" . }}
                  key: MILVUS_TOKEN
          volumeMounts:
            - name: run-override
              mountPath: /app/run.yaml
              subPath: run.yaml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: run-override
          configMap:
            name: {{ include "my-llama-stack.fullname" . }}
            items:
              - key: run.yaml
                path: run.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
