apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-llama-stack.fullname" . }}-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /lls_storage
    server: rack.home.glroland.com
  storageClassName: {{ include "my-llama-stack.fullname" . }}-pv-storage-class
