apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-llama-stack.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
