apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-llama-stack.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: {{ include "my-llama-stack.fullname" . }}-pv-storage-class
