pipeline 
{
   agent any
   
   options 
   {
      disableConcurrentBuilds()
      buildDiscarder(logRotator(numToKeepStr: '3'))
   }

   stages
   {
      stage('Prepare') 
      {
         steps 
         {
            sh '''
                    echo "PATH = ${PATH}"
                '''

            git branch: 'main', 
                url: 'https://github.com/glroland/my-llama-stack.git'
         }
      }

      stage('Prepare for LLama Stack Build') 
      {
         steps 
         {
            dir('target')
            {
               // recreate artifact directory
               deleteDir()
               sh 'pwd -P'
               
               // install the dependencies
               sh """
                  uv venv my-llama-stack --python 3.12
                  . my-llama-stack/bin/activate
                  uv pip install -r ../requirements.txt
                  """
            }
         }
      }

      stage('Build Llama Stack Image') 
      {
         steps 
         {
            sh """
               . target/my-llama-stack/bin/activate
               llama stack build --config build.yaml --image-type container --image-name distribution-my-llama-stack
               """
         }
      }

      stage('Build LLama Stack UI Image') 
      {
         steps 
         {
            sh 'docker build -t my-llama-stack-ui:$BUILD_NUMBER -f Dockerfile.ui_override .'
         }
      }

      stage('Publish Llama Stack Image') 
      {
         steps 
         {
            sh 'docker tag distribution-my-llama-stack:0.2.21 my-llama-stack:$BUILD_NUMBER'
            sh 'docker save my-llama-stack:$BUILD_NUMBER > my-llama-stack-dockerimage.tar'
            step(followSymlinks: false, artifacts: 'my-llama-stack-dockerimage.tar', $class: 'ArtifactArchiver')
            sh 'docker rmi my-llama-stack:$BUILD_NUMBER'
            sh 'docker rmi distribution-my-llama-stack:0.2.21'
         }
      }

      stage('Publish Llama Stack UI Image') 
      {
         steps 
         {
            sh 'docker save my-llama-stack-ui:$BUILD_NUMBER > my-llama-stack-ui-dockerimage.tar'
            step(followSymlinks: false, artifacts: 'my-llama-stack-ui-dockerimage.tar', $class: 'ArtifactArchiver')
            sh 'docker rmi my-llama-stack-ui:$BUILD_NUMBER'
         }
      }

      stage('Reload then push LLama Stack image to quay') 
      {
         steps 
         {
            script 
            {
               docker.withRegistry('https://registry.home.glroland.com/', 'quay') 
               {
                  sh 'docker load -i my-llama-stack-dockerimage.tar'
                  sh 'docker tag my-llama-stack:$BUILD_NUMBER registry.home.glroland.com/ai/my-llama-stack:$BUILD_NUMBER'
                  sh 'docker rmi my-llama-stack:$BUILD_NUMBER'
                  sh 'docker push registry.home.glroland.com/ai/my-llama-stack:$BUILD_NUMBER'
                  sh 'docker rmi registry.home.glroland.com/ai/my-llama-stack:$BUILD_NUMBER'
               }
            }
         }
      }

      stage('Reload then push LLama Stack UI image to quay') 
      {
         steps 
         {
            script 
            {
               docker.withRegistry('https://registry.home.glroland.com/', 'quay') 
               {
                  sh 'docker load -i my-llama-stack-ui-dockerimage.tar'
                  sh 'docker tag my-llama-stack-ui:$BUILD_NUMBER registry.home.glroland.com/ai/my-llama-stack-ui:$BUILD_NUMBER'
                  sh 'docker rmi my-llama-stack-ui:$BUILD_NUMBER'
                  sh 'docker push registry.home.glroland.com/ai/my-llama-stack-ui:$BUILD_NUMBER'
                  sh 'docker rmi registry.home.glroland.com/ai/my-llama-stack-ui:$BUILD_NUMBER'
               }
            }
         }
      }
   }
}
