apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-llama-stack.fullname" . }}
  labels:
    {{- include "my-llama-stack.labels" . | nindent 4 }}
immutable: false
data:
  FIREWORKS_API_KEY: ""
  TOGETHER_API_KEY: ""
  SAMBANOVA_API_KEY: ""
  OPENAI_API_KEY: "nokeyneeded"
  TAVILY_SEARCH_API_KEY: ""
